services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_NAME
      - GF_SERVER_ROOT_URL
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GRAFANA_SMTP_USER
      - GRAFANA_SMTP_PASSWORD
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./grafana-config/grafana.ini:/etc/grafana/grafana.ini:ro


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config:/etc/prometheus:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    extra_hosts:
      # used to hit locally deployed services
      - "host.docker.internal:host-gateway"


  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - 3100:3100
    volumes:
      - ./loki-config/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yaml


  alloy:
    # ref: https://grafana.com/docs/alloy/latest/set-up/install/docker/
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    ports:
      - 12345:12345
    volumes:
      - ./alloy-config/config.alloy:/etc/alloy/config.alloy:ro
      - alloy-data:/var/lib/alloy/data
      - /var/log:/host/var/log:ro
      - /run/log/journal:/host/run/log/journal:ro
    command: 'run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy'



volumes:
  prometheus-data:
  grafana-data:
  loki-data:
  alloy-data:

