[smtp]
# setup proton mail with an SMTP token auth
enabled = true
host = smtp.protonmail.ch:587
user = $__env{GRAFANA_SMTP_USER}
password = $__env{GRAFANA_SMTP_PASSWORD}
from_address = admin@proton.grumpy-gnome.club
from_name = Grafana Alerts
startTLS_policy = MandatoryStartTLS
